{
 "title": "Aerospike Cluster",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Memory Free Percent",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "memory_free_pct", "legendFormat": "{{node}}:{{namespace}}" }
   ]
  },
  {
   "title": "Master Objects - ns1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(master_objects{namespace=\"ns1\"})"
    }
   ]
  },
  {
   "title": "Master Objects-ns2",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 3 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(master_objects{namespace=\"ns2\"})"
    }
   ]
  },
  {
   "title": "Device Available Percent",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    { "expr": "device_available_pct", "legendFormat": "{{node}}:{{namespace}}" }
   ]
  },
  {
   "title": "Device Used Pct",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    { "expr": "(100-device_free_pct)", "legendFormat": "{{node}}:{{namespace}}" }
   ]
  },
  {
   "title": "Cluster Size Reported by Each Node",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 6 },
   "targets": [
    { "expr": "cluster_size", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "CLOCK SKEW STOP WRITES",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "targets": [
    { "expr": "clock_skew_stop_writes", "legendFormat": "{{node}}:{{namespace}}" }
   ]
  },
  {
   "title": "STOP WRITES",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 12 },
   "targets": [
    { "expr": "stop_writes", "legendFormat": "{{node}}:{{namespace}}" }
   ]
  },
  {
   "title": "HWM BREACHED",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 12 },
   "targets": [
    { "expr": "hwm_breached", "legendFormat": "{{node}}:{{namespace}}" }
   ]
  },
  {
   "title": "Evicted Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(evicted_objects{namespace=\"ns1\"})by(node)",
     "legendFormat": "ns1:{{node}}"
    },
    {
     "expr": "sum(evicted_objects{namespace=\"ns2\"})by(node)",
     "legendFormat": "ns2:{{node}}"
    },
    {
     "expr": "sum(evicted_objects{namespace=\"ns1\"})",
     "legendFormat": "Total:ns1"
    },
    {
     "expr": "sum(evicted_objects{namespace=\"ns2\"})",
     "legendFormat": "Total:ns2"
    }
   ]
  }
 ]
}