local function aggregate_stats(map,rec)
  -- Exercise 1
  -- NOTE: rec will include 'region' bin of type string and the valid values are 'n', 's', 'e', 'w'
  -- TODO: Examine value of 'region' bin in record rec and increment respective counter in the map
  -- TODO: return updated map
end

local function reduce_stats(a,b)
  -- Exercise 1
  -- TODO: Merge values from map b into a
  -- TODO: Return updated map a
end

function sum(stream)
  -- Exercise 1
  -- TODO: Process incoming record stream and pass it to aggregate function, then to reduce function
  --   NOTE: aggregate function aggregate_stats accepts two parameters: 
  --    1) A map that contains four variables to store number-of-users counter for north, south, east and west regions with initial value set to 0  
  --    2) function name aggregate_stats -- which will be called for each record as it flows in
  -- TODO: Return reduced value of the map generated by reduce function reduce_stats
end
