apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: k8Training
  region: us-east-1
  version: "1.18"

iam:
  withOIDC:

managedNodeGroups:
  - name: ng-1
    instanceType: t2.small
    minSize: 1
    maxSize: 10 #Optional
    desiredCapacity: 2 #Start with 2 worker nodes
    volumeSize: 20
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      publicKeyName: myKeyPair
