local function aggregate_stats(mapObj,rec)
  -- Exercise A1
  -- NOTE: rec will include 'region' bin of type string and the valid values are 'n', 's', 'e', 'w'
  -- rec is aerospike lua record type. It has various methods available to
  -- get the digest and the metadata as well as update the record.
  -- mapObj is what we passed to aggregate_stats as an aerospike lua map type.
  -- TODO: Examine value of 'region' bin in record rec and increment respective counter in the mapObj
  -- TODO: return updated mapObj
end

local function reduce_stats(a,b)
  -- Exercise A1
  -- TODO: Merge values from map b into a
  -- TODO: Return updated map a
end

function sum(stream)
  -- Exercise A1
  -- TODO: Process incoming record stream and pass it to aggregate function, then to reduce function
  --   NOTE: aggregate function aggregate_stats accepts two parameters: 
  --    1) A map that contains four variables to store number-of-users counter for 
  --    north, south, east and west regions with initial value set to 0  
  --    2) function name aggregate_stats -- which will be called for each record as it flows in
  -- TODO: Return reduced value of the map generated by reduce function reduce_stats

  -- Note: You must use the aerospike lua module defined types so you can return back to the client in
  --       recognized types. Use map type instead of Lua table type here.
end
